loanApp/urls.py
from django.urls import path
from loanApp import views


app_name = 'loanApp'
urlpatterns = [
    path('loan-request/', views.LoanRequest, name='loan_request'),
    path('loan-payment/', views.LoanPayment, name='loan_payment'),
    path('user-transaction/', views.UserTransaction, name='user_transaction'),
    path('user-loan-history/', views.UserLoanHistory, name='user_loan_history'),
    path('user-dashboard/', views.UserDashboard, name='user_dashboard'),

]

loan_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from loanApp import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('loginApp.urls')),
    path('loan/', include('loanApp.urls')),
    path('manager/', include('managerApp.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'loanApp.views.error_404_view'

loginApp/urls.py
from django.urls import path
from loginApp import views


app_name = 'login_App'
urlpatterns = [
    path('login-customer/', views.login_view, name='login_customer'),
    path('signup-customer/', views.sign_up_view, name='signup_customer'),
    path('logout-customer/', views.logout_view, name='logout'),
    path('edit-customer/', views.edit_customer, name='edit-customer'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/735bf95db2.js" crossorigin="anonymous"></script>


    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
    <title>

        {% block title_block %}

        {% endblock %}
    </title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    {% block block_js %}

    {% endblock %}


    {% block css_block %}

    {% endblock %}
</head>

<body>

    {% block body_block %}


    {% endblock %}

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script

</body>

</html>

templates/error.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
Error
{% endblock %}

{% block body_block %}
{% include 'navbar.html' %}

<div class="my-5 conatiner">
    <div class="row">
        <div class="m-auto col-md-4">
            <div class="text-center alert alert-danger" role="alert">
                {{error}}
            </div>
        </div>
    </div>
</div>

{% include 'footer.html'%}

{% endblock %}

templates/footer.html
{% extends 'base.html' %}

{% load static %}

{% block css_block %}

<style>

</style>

{% endblock %}

{% block body_block %}



<footer class="text-center text-white bg-light">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
                <!-- Section: Social media -->
                <section class="mb-4">
                        <!-- Facebook -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #3b5998;" href="#!"
                                role="button"><i class="fab fa-facebook-f"></i></a>

                        <!-- Twitter -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #55acee;" href="#!"
                                role="button"><i class="fab fa-twitter"></i></a>

                        <!-- Google -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #dd4b39;" href="#!"
                                role="button"><i class="fab fa-google"></i></a>

                        <!-- Instagram -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #ac2bac;" href="#!"
                                role="button"><i class="fab fa-instagram"></i></a>

                        <!-- Linkedin -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #0082ca;" href="#!"
                                role="button"><i class="fab fa-linkedin-in"></i></a>
                        <!-- Github -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #333333;" href="#!"
                                role="button"><i class="fab fa-github"></i></a>
                </section>
                <!-- Section: Social media -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="p-3 text-center text-dark" style="background-color: rgba(0, 0, 0, 0.2);">
                © 2021 Copyright
                <a class="text-dark" target="_blank" href="https://www.nahidjc.xyz/">Nahid Hasan</a>
        </div>
        <!-- Copyright -->
</footer>


{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block css_block %}


<style>
    .row {
        height: 80vh;

    }
</style>
{% endblock %}

{% block body_block %}

{% include 'navbar.html' %}

<div class="container">
    <div class="row">
        <div class="col-md-6 m-auto">
            <img src="{% static 'images/loan.jpg' %}" class="img-fluid mx-auto" alt="Background Image" srcset="">

        </div>
        <div class="col-md-6 m-auto">
            <div class="d-flex justify-content-center align-items-center">
                <a href="/loan/loan-request/">
                    <button type="button" class="btn btn-info btn-rounded m-2">Apply Loan</button>
                </a>

                or
                <a href="/account/signup-customer/">

                    <button type="button" class="btn btn-info btn-rounded ms-2">Register</button>
                </a>

            </div>

        </div>
    </div>
</div>



{% include "footer.html" %}
{% endblock %}

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
{% load bootstrap4 %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
    <!-- MDB -->


    <title></title>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Navbar brand -->
                <a class="mt-2 navbar-brand mt-lg-0" href="/">
                    <img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" height="15" alt=""
                        loading="lazy" />
                </a>
                <!-- Left links -->
                <ul class="mb-2 navbar-nav me-auto mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="/">HOME</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/loan/user-dashboard">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/loan/user-loan-history">Loan History</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'loanApp:loan_payment' %}">Pay Loan</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/loan/user-transaction">Transactions</a>
                    </li>
                    {% endif %}


                </ul>
                <!-- Left links -->

                <ul class="mb-2 navbar-nav ms-auto mb-lg-0">
                    {% if user.is_authenticated %}

                    <li>
                        <a class="nav-link" href="{% url 'loanApp:loan_request'%}">Apply Loan</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'login_App:edit-customer'%}">Edit Info</a>
                    </li>

                    <li>
                        <a class="nav-link" href="/account/logout-customer">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item me-2">
                        <b> <a class="nav-link" href="/account/login-customer">Login</a></b>


                    </li>
                    <li class="nav-item">
                        <b> <a class="nav-link" href="/account/signup-customer">Signup</a></b>
                    </li>
                    <li class="nav-item">
                        <b> <a class="nav-link" href="/manager/admin-login">Admin</a></b>
                    </li>

                    {% endif %}

                </ul>
            </div>
            <!-- Collapsible wrapper -->



            <!-- Right elements -->
            <div class="d-flex align-items-center">







            </div>
            <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>

</body>

</html>

templates/notFound.html
{% extends 'base.html' %}
{% load static %}

{% block css_block %}


{% endblock %}

{% block body_block %}

{% include 'navbar.html' %}
<header class='container'>


    <!-- Jumbotron -->
    <div class="p-5 text-center alert alert-danger" role="alert">
        <h1 class="mb-3">Page Not Found</h1>
        <h4 class="mb-3">Sorry the page is missing or doesn't exist</h4>
        <a class="btn btn-primary" href="/" role="button">Home Page</a>
    </div>
    <!-- Jumbotron -->
</header>

{% include "footer.html" %}
{% endblock %}

templates/plugin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/735bf95db2.js" crossorigin="anonymous"></script>


    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</head>

<body>



    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script

</body>

</html>